export const fakePlayers = [
  {
    id: 1,
    name: "M. Sarfaraj",
    dob: "1997-07-01",
    position: "DF",
    playsFor: "The Boss FC",
    appearances: 38,
    goals: 31,
    assists: 8,
    preferredFoot: "Right",
    image: "https://i.ibb.co.com/JwWHJ2gx/m-sarfaraj.png",
  },
  {
    id: 2,
    name: "L. Kabir",
    dob: "1997-07-01",
    position: "GK",
    playsFor: "Ancholuti FC",
    appearances: 38,
    goals: 31,
    assists: 8,
    preferredFoot: "Left",
    image: "https://i.ibb.co.com/JwWHJ2gx/m-sarfaraj.png",
  },
  {
    id: 3,
    name: "M. Nayeem",
    dob: "1997-08-07",
    position: "MF",
    playsFor: "Ancholuti FC",
    appearances: 8,
    goals: 3,
    assists: 1,
    preferredFoot: "Rignt",
    image: "https://i.ibb.co.com/4gRWc0bq/m-nayeem.png",
  },
  {
    id: 4,
    name: "M. Hayan",
    dob: "1997-08-07",
    position: "FW",
    playsFor: "The Boss FC",
    appearances: 38,
    goals: 31,
    assists: 8,
    preferredFoot: "Rignt",
    image: "https://i.ibb.co.com/tPLvzVvq/image.png",
  },
  {
    id: 5,
    name: "T. Nibir",
    dob: "1997-08-07",
    position: "FW",
    playsFor: "Ancholuti FC",

    appearances: 38,
    goals: 31,
    assists: 8,
    preferredFoot: "Rignt",
    image: "https://i.ibb.co.com/tPLvzVvq/image.png",
  },
  {
    id: 6,
    name: "V. Opu",
    dob: "1997-08-07",
    position: "MF",
    playsFor: "Ancholuti FC",

    appearances: 38,
    goals: 31,
    assists: 8,
    preferredFoot: "Rignt",
    image: "https://i.ibb.co.com/tPLvzVvq/image.png",
  },
];
